---
bool success
string message
bool safety_fault
string safety_reason
string homing_state
bool[5] online
bool[5] enabled_ok
bool[5] enabled
bool[5] stalled
bool[5] raw35_ok
bool[5] angle_error_ok
int64[5] enc31
int64[5] raw35
float32[5] position_mm
float32[5] velocity_mm_s
int32[5] angle_error
uint8[5] home91
uint8[5] home3b_single
uint8[5] home3b_origin
bool[3] limits_configured
float32[3] limit_min_mm
float32[3] limit_max_mm
